### ISSUE TITLE
Support for multiple authors with different affiliation

### ISSUE THREAD

**Issue by ZihengJiang** [MCG-NKU/CVPR_Template#10]
Is it possible to support something like this?
https://tex.stackexchange.com/questions/9594/adding-more-than-one-author-with-different-affiliation

I tried to use `authblk`, but it seems will make the overleaf stuck forever while used in this template.

**Comment by CalciferZh** [comment]
@ZihengJiang Hi, have you solved this issue? Thanks in advance.

**Comment by ZihengJiang** [comment]
Nope, I use other tricks to add authors instead of `authblk` in the end

**Comment by Hanzy1996** [comment]
Hi, @ZihengJiang!
I had the same issue when using authblk. Could you please share what tricks did you use?

Best wishes!
